package entity;
// Generated Jun 29, 2020 6:00:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblconference generated by hbm2java
 */
public class Tblconference  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String overview;
     private String description;
     private String address;
     private int limit;
     private String participant;
     private Date startTime;
     private Date endTime;

    public Tblconference() {
    }

    public Tblconference(String name, String overview, String description, String address, int limit, String participant, Date startTime, Date endTime) {
       this.name = name;
       this.overview = overview;
       this.description = description;
       this.address = address;
       this.limit = limit;
       this.participant = participant;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getLimit() {
        return this.limit;
    }
    
    public void setLimit(int limit) {
        this.limit = limit;
    }
    public String getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(String participant) {
        this.participant = participant;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}


