package entity;
// Generated Jul 13, 2020 1:29:27 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblconference generated by hbm2java
 */
public class Tblconference  implements java.io.Serializable {


     protected Integer id;
     protected String name;
     protected String overview;
     protected String description;
     protected String address;
     protected int limit;
     protected Date startTime;
     protected Date endTime;

    public Tblconference() {
    }

    public Tblconference(String name, String overview, String description, String address, int limit, Date startTime, Date endTime) {
       this.name = name;
       this.overview = overview;
       this.description = description;
       this.address = address;
       this.limit = limit;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getLimit() {
        return this.limit;
    }
    
    public void setLimit(int limit) {
        this.limit = limit;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


