package entity;
// Generated Jul 15, 2020 11:08:41 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblconference generated by hbm2java
 */
public class Tblconference  implements java.io.Serializable {


     protected Integer id;
     protected String name;
     protected String overview;
     protected String description;
     protected int locationId;
     protected Date startTime;
     protected Date endTime;

    public Tblconference() {
    }

    public Tblconference(String name, String overview, String description, int locationId, Date startTime, Date endTime) {
       this.name = name;
       this.overview = overview;
       this.description = description;
       this.locationId = locationId;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


