package entity;
// Generated Jul 15, 2020 11:08:41 AM by Hibernate Tools 4.3.1



/**
 * Tbllocation generated by hbm2java
 */
public class Tbllocation  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int myLimit;

    public Tbllocation() {
    }

    public Tbllocation(String name, int myLimit) {
       this.name = name;
       this.myLimit = myLimit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getMyLimit() {
        return this.myLimit;
    }
    
    public void setMyLimit(int myLimit) {
        this.myLimit = myLimit;
    }




}


