package entity;
// Generated Jul 15, 2020 11:08:41 AM by Hibernate Tools 4.3.1



/**
 * Tblregisterconference generated by hbm2java
 */
public class Tblregisterconference  implements java.io.Serializable {


     private Integer id;
     private int idConference;
     private int idUser;
     private int status;

    public Tblregisterconference() {
    }

    public Tblregisterconference(int idConference, int idUser, int status) {
       this.idConference = idConference;
       this.idUser = idUser;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(int idConference) {
        this.idConference = idConference;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


