package entity;
// Generated Jul 13, 2020 1:29:27 PM by Hibernate Tools 4.3.1



/**
 * Tbluser generated by hbm2java
 */
public class Tbluser  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String username;
     private String password;
     private int roleId;
     private boolean isDeleted;

    public Tbluser() {
    }

    public Tbluser(String name, String email, String username, String password, int roleId, boolean isDeleted) {
       this.name = name;
       this.email = email;
       this.username = username;
       this.password = password;
       this.roleId = roleId;
       this.isDeleted = isDeleted;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


